### ISSUE TITLE
Google cloud Exporter stops sending logs when there is high memory usage in collector and never restarts.

### ISSUE THREAD

**Issue by davidgargti20** [GoogleCloudPlatform/opentelemetry-operations-go#449] opened 2022-07-05 17:30 UTC

**Comment by damemi** [comment] 2022-07-06 15:31
Can you please share some more information? For example:
* memory usage you are seeing
* approx. ingestion/throughput
* collector config settings you've tried (such as batch/memory limiter)

**Comment by davidgargti20** [comment] 2022-07-06 18:23
while using a batch processor when memory rises above 1 gb it stops
with batch memory_limiter if memory limiter is around 500mb it works but drops logs
but when batch memory_limiter is set to above 1gb it stops

**Comment by damemi** [comment] 2022-07-07 16:58
@davidgargti20 could you share the actual config YAML for the collector? That would make it easier for me to understand your settings, and also see if you're doing other operations on the entries in your pipeline that might be causing this (you can remove any sensitive strings if you need to)

We've done some stress testing on this ourselves and found it to be able to comfortably process up to around 75mb/s of logs data. Are you working with a higher rate than that?

**Comment by davidgargti20** [comment] 2022-07-07 18:33
@damemi it could also be much better that shows that this limit is reaching or something that could be quite useful. 
Also do tell me if there is certain way that could allow me to send logs on higher limit.

**Comment by damemi** [comment] 2022-07-12 15:35
@davidgargti20 this isn't a limit we're imposing, it's a technical limitation of the underlying libraries. We're still investigating potential high-cost operations that could be optimized, but due to that we don't have a good way to identify when this limit could be reached unfortunately.

**Comment by damemi** [comment] 2022-08-02 14:56
Our teams did some more stress testing on this, and while we do eventually see some diminished throughput, we haven't been able to reach a point where the exporter completely shuts down. In fact, in isolated tests we've actually seen the exporter reach over 200MB/s of throughput.

Granted, these tests are done with basic logs (each line 1024 bytes in size). We did find that additional processors can cause a "backpressure" buildup that slowed the throughput gradually, especially when combined with the filelogreceiver (which only processes 1 entry at a time). I believe the transform processor is based on some of the same Stanza libraries, so it would make sense that this backpressure effect would show up. 

It looks like you are making heavy use of the transform processor, so that combined with your overall throughput and batch settings could be the cause for this. However, without a more accurate replica setup (eg, a sample of your log formats + approximate collection rate) we won't be able to reproduce this.

If you can provide those things, we could try once more to reproduce this. Otherwise, I'm going to close this issue and we can reopen if it comes up again. This will be a valuable reference in that case, so thank you for the information you have provided already.

**Closed** 2022-08-05 14:25 UTC
