### ISSUE TITLE
Install the OpenTelemetry package fails with `undefined: "go.opentelemetry.io/otel/sdk/export/trace".SpanData`

### ISSUE THREAD

**Issue by RyanBalfanz** [GoogleCloudPlatform/opentelemetry-operations-go#133] opened 2021-01-21 20:01 UTC
From Using OpenTelemetry with Go docs, [Install the OpenTelemetry package:](https://cloud.google.com/trace/docs/setup/go-ot#install-client)

```
go get -u go.opentelemetry.io/otel
go get -u github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace
```

```
$ go get -u go.opentelemetry.io/otel
$ go get -u github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace
# github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace
/Users/ryanbalfanz/go/src/github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace/cloudtrace.go:40:33: undefined: "go.opentelemetry.io/otel/sdk/export/trace".SpanData
/Users/ryanbalfanz/go/src/github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace/cloudtrace.go:325:65: undefined: "go.opentelemetry.io/otel/sdk/export/trace".SpanData
/Users/ryanbalfanz/go/src/github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace/cloudtrace.go:345:53: undefined: "go.opentelemetry.io/otel/sdk/export/trace".SpanData
/Users/ryanbalfanz/go/src/github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace/trace.go:119:59: undefined: "go.opentelemetry.io/otel/sdk/export/trace".SpanData
/Users/ryanbalfanz/go/src/github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace/trace_proto.go:60:29: undefined: "go.opentelemetry.io/otel/sdk/export/trace".SpanData
/Users/ryanbalfanz/go/src/github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace/trace_proto.go:73:36: undefined: "go.opentelemetry.io/otel/sdk/export/trace".SpanData
/Users/ryanbalfanz/go/src/github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace/trace_proto.go:90:27: undefined: "go.opentelemetry.io/otel/sdk/export/trace".SpanData
```

**Comment by dashpole** [comment] 2021-01-22 16:47
Duplicate of https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/131.  You can pin otel to v0.15.0 in the meantime to work around this.

**Closed by dashpole** 2021-01-22 16:47 UTC

**Comment by RyanBalfanz** [comment] 2021-01-22 21:18
Thanks, @dashpole. I'll have a look there.

**Comment by RyanBalfanz** [comment] 2021-01-22 21:18
> Duplicate of #131. You can pin otel to v0.15.0 in the meantime to work around this.

Thanks, @dashpole. I'll have a look there.

**Comment by RyanBalfanz** [comment] 2021-01-22 21:19
> > Duplicate of #131. You can pin otel to v0.15.0 in the meantime to work around this.
> 
> Thanks, @dashpole. I'll have a look there.

By the way, I looks at #131 just now and it's not super clear to me that it's a duplicate of this issue since there's not much information on the issue.
