### ISSUE TITLE
moved: go.opentelemetry.io/otel/sdk/metric/controller/push

### ISSUE THREAD

**Issue by xmlking** [GoogleCloudPlatform/opentelemetry-operations-go#132] opened 2021-01-20 18:28 UTC
whiled testing with `go.opentelemetry.io/otel v0.16.0`, I am getting this error.
may be we need to upgrade deps in this module 
```
go: finding module for package go.opentelemetry.io/otel/sdk/metric/controller/push
/Users/sxc460/go/pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/metric@v0.15.0/metric.go:31:2: module go.opentelemetry.io/otel/sdk@latest found (v0.16.0), but does not contain package go.opentelemetry.io/otel/sdk/metric/controller/push
make: *** [test] Error 1

```

**Comment by dashpole** [comment] 2021-01-22 16:48
Duplicate of https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/131.  You can pin otel to v0.15.0 in the meantime to work around this.  You can follow that issue to track the release.

**Closed by dashpole** 2021-01-22 16:48 UTC
